### PR TITLE
WIP Feature mcr switch planners

### PR DESCRIPTION
**Pull request by jcmayoral**
Adding feature to update planners on move_base navigation stack

### CODE REVIEW

**Comment by jcmayoral** [comment]
@alex-mitrevski @argenos I think the minimum things are already here. I still need to manage some errors (if the planners does not exists or if the desired planner is already in use). But what do you think?

**Comment by jcmayoral** [comment]
I provided two test scripts how to use it. I think it is not really necessary to have a addiitional thread to provide to a service, since it is basically parameter configuration but if it is required I can add it. Moreover, I add for now most of the magic in the constructor, . I have already tested the update_planner.py (but I just provide some config samples files for it). The mode_planner_update.py should work but no time to test yet.

**Comment by argenos** [comment]
@jcmayoral the email address for some of your commits is not listed in your GitHub e-mail addresses. Since it's only you working in this branch, you can fix it by [rebasing](https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit) or just by adding your other email address to your GitHub profile if you want. The latter is the easiest, if you have no problems with that email being linked there ;)

**Comment by jcmayoral** [comment]
ok. That was for sure an intersting git experience. Thanks @argenos , I will finish this as soon as I have enough time to do it.

**Comment by argenos** [comment]
@sthoduka what do we want to do with this PR? merge it or close it?

**Pull request closed without merging**
